table People
	lineageTag: 2211a4ce-a477-4674-9361-3a2df363429d

	column Person
		dataType: string
		lineageTag: 55b872ec-3f7c-4ad1-bad8-4b2e6dfc4bcc
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 722be1d1-bf89-4ab5-9393-5817310d3b73
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition People-0232ef1a-2f3c-4551-a88d-a1ddc286cd16 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\M1097481\Downloads\Sample - Superstore csv.xlsx"), null, true),
				    People_Sheet = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

