table Sheet1
	lineageTag: 1ccd45e6-0518-4927-9bc4-5f0de128e9b0

	column 'Applied filters:Manager is Tejasvi ChintalaTechnical Advisor is Reeyareddy.VType is CaseType is Case, CollaborationTasks, or EscalationTasks'
		dataType: string
		lineageTag: 6f9636dc-b8c2-4739-9648-3075fc96c00b
		summarizeBy: none
		sourceColumn: Applied filters:Manager is Tejasvi ChintalaTechnical Advisor is Reeyareddy.VType is CaseType is Case, CollaborationTasks, or EscalationTasks

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 17de95f8-227d-4586-9b04-43414e2954d8
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: d01cedd4-86fc-4348-a422-a48055fae6f9
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 7c5827fa-0bc7-4722-afe1-33354b0c52bc
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: b3d3f8b2-11b2-4b37-8702-6ce4622b7ddf
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 3f0b776c-7e17-4a54-bcc8-e9a09243f055
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 7ded1d9b-e31d-4f33-8e83-4f703f5d66e9
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 7a643a70-8e31-4840-918a-59314851a903
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 3bdb6f51-9152-4d60-bf72-2f4f29304a9c
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: f11446ac-39d3-47b5-9db2-50b05c2caf4e
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 89b322f1-53c6-479c-aece-1eef07983fb3
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: f86f0108-e08c-4c6b-8253-88e43d1393dc
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 2ec6e812-b4f1-4809-845c-b20ebafc3f4c
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 0e08f5a4-df17-4001-b875-1bd35dbb129a
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 6b09bc5a-9825-4627-8e9c-df4b4defbf42
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 498f4eca-f8fe-4cd1-8f4d-30b0d2c8e2ad
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 375dc1ec-756e-417b-8005-4cbf92de9351
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 24beebb0-782f-4bff-9599-5d5eb55cb048
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	partition Sheet1-641842ff-7091-49a1-8a96-205fc3f469b1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\v-kuberpujar\Downloads\15th July.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Applied filters:#(lf)Manager is Tejasvi Chintala#(lf)Technical Advisor is Reeyareddy.V#(lf)Type is Case#(lf)Type is Case, CollaborationTasks, or EscalationTasks", type any}, {"Column2", type text}, {"Column3", type any}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type text}, {"Column13", type text}, {"Column14", type any}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

