table Orders
	lineageTag: dfdcd689-c9db-4a3a-af5a-f8b2341bebbb

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 488a2382-9951-4806-9002-f1aa23dc6910
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 9d1e20da-de0b-46ea-adb7-2681f824f2ff
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: acaae335-97f5-4bdd-a737-42f4cfc8973c
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 491e2824-4bd2-4be5-9b13-953bcc45ce45
			defaultHierarchy: LocalDateTable_da99a733-e28c-47f9-bd45-15b6c90af74f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d19a58c-70b3-485b-a6cb-f11d561aced8
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 4fb73cba-9d90-4d2c-991b-1b51a977f143
			defaultHierarchy: LocalDateTable_c6d3a944-c099-463f-ae02-f1a1700ac166.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: f8191dff-9332-43aa-8f14-3c3e0b4385ff
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 009c61d1-e022-427f-b198-4324b2d07b71
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: eaf43bc3-5b58-479e-aa80-03eb22039ffa
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 4afc0ddc-bbdf-479b-9bc1-bb3b57d81548
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 73393e26-8124-44f2-a488-a4cb392f5026
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e0887fab-cac4-4a74-9876-ad3d5df376b0
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a47da31c-086c-4d18-a691-1ef4a59cc6b1
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 4b3cc6e9-4948-45d7-87ab-751feb3fbbe7
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 528d1d31-2534-49c3-9ec1-658dd0bbfc13
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: c2f7ca26-0267-4688-82ad-d0d43840dae8
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 76b28ed8-7cca-41fa-8081-4006e3bf5b07
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: d31d1c29-5c6f-4f5e-82c5-666da5e967ba
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 6aba52c1-7528-4891-9aa4-b38d1ffbb8e1
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 5d6870c7-bc85-48c3-95f5-e560df848f67
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 85107e03-c551-4c9d-ad83-dc7b9f6105e1
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 4d41c863-8dee-4e7a-903e-0d1b40c34557
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 12e9848a-a27f-47ec-8b30-957ed40bd1e9
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders-6fdc5544-dd92-4665-81c0-3786376bc976 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Aman\Desktop\Sample - Superstore.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

