table Orders
	lineageTag: f088ee7e-0d5a-4c17-8c4e-35e3bd010454

	measure fregion = CALCULATE(SUM(Orders[Sales]),Orders[Region]="East")
		lineageTag: d40db8cf-a3c3-4a85-88d1-4f394bf36c16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: dc94d973-1928-439c-acb9-465aea200cdc
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: ed158b89-abd5-45d8-a6c9-e281cb4383b7
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1c160b9-e1d5-41c7-8193-c665a6fc2164
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: f99626da-0df3-494a-bfc8-4f9b6773583f
			defaultHierarchy: LocalDateTable_be004647-b73f-42e4-8808-1a69dbde66f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad52db9b-b8d8-40a5-9563-b6b8b2de2fba
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: be51bbb2-884d-45eb-b46c-d4439846cf52
			defaultHierarchy: LocalDateTable_fe007305-6880-4503-90db-07af25375056.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 768d57cc-0e19-4422-a965-236620aa42e3
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 51c2e9fb-ea94-4ac8-b908-8af92586d71b
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ed427260-cd31-4e23-858a-54a93e94fcdf
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 3571e364-0f1d-4579-8834-228e52e5e674
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a418be69-f1fe-4c27-b813-aaee66af7f5a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: a8623639-7b3b-45b5-9666-f2ca044bd0a1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 590329ea-81cc-49b2-b5e4-68c612eee311
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 699b3324-b0ed-49bb-a832-7921fa13fcf0
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: e2dcffe1-33c5-47bc-b804-4570883e6d1e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 69dd3286-9f8b-4ea9-92e3-ef94af2bfa3c
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: df2839e7-b177-41e1-ad1b-75d1f642cc5b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: eb7c5536-e2a3-4671-96fa-17072c701e71
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: f1896ade-460d-4a4d-bd75-dbb66ffa83e6
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: bcfa8dc5-c3d7-4f86-bcb5-3a18d3af81db
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: fb801eb8-a472-4518-94c1-451e002576ea
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: b2684090-594c-46ca-b6c3-d809ae963cae
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 79e4c3a3-ad2f-47b0-8752-981cf1ba58c5
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders-92180d7f-7862-4701-930d-7fe69e7ec822 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Aman\Desktop\Sample - Superstore.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

