table Returns
	lineageTag: 481cb8d3-8d7c-4870-aa91-75f72554bbc4

	column Returned
		dataType: string
		lineageTag: 1c6b21b2-bcf5-4681-be32-7a7702103856
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 96a84a41-6357-40b8-85f0-e67f53d04563
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	partition Returns-d52ace9b-b158-400b-bc9c-c7b38519f5a8 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Aman\Desktop\Sample - Superstore.xlsx"), null, true),
				    Returns_Sheet = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Returns_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Returned", type text}, {"Order ID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

