table Orders
	lineageTag: 9f0c58eb-5ac6-464c-96b1-532674b0cef3

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 85856057-ff51-4bab-816f-aa2fbc280196
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 58641172-e29c-4f6c-8d27-08f7d927b088
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e73a5151-b43d-49dd-b03b-0e3125409219
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 3a4562fe-46a6-42b7-8472-d992fce00798
			defaultHierarchy: LocalDateTable_65109749-851f-4973-b0b3-bd5894377677.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb0cf474-6692-4c9d-88fd-9dc2daa97222
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: f0d2fa46-259b-485e-99b1-6cf6d4b76380
			defaultHierarchy: LocalDateTable_dafdcf5a-3c68-41fd-b937-351293ea1b0c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 5932d8c6-e25e-48cf-bd73-18d721478510
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2de1d794-cad5-47d9-93f1-a62e1615b5a6
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: e32a2324-7581-4e8e-8c55-35e78bfb39a9
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 08a9f0b2-9e34-432e-914c-ee07521083ca
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 4267101c-5248-43f1-9d0c-337cbb11977a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 3d58b436-518e-4d03-84c9-853021b413e1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: fbffa62a-f31f-4beb-a297-305a7690d435
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: a3b2c65c-c064-4d94-a0c1-8dc534e8b2f6
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: aadb0ddb-bc77-4669-a98e-34e740643994
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 32aee960-cad4-4f65-add9-523a8a949987
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 764324a7-f0df-46dc-91d4-ef05dcc75d83
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 9b7465fd-36e6-42f1-a9f3-b8626c16d4a5
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 13d1f5de-0124-4781-aedf-4c022501b3d0
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 6fe2968b-98e9-47e4-8cd3-8f0f3c759a92
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: be521d36-c483-453b-954b-66a6d44489c9
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 92b421bb-498c-473a-aff4-2d11ac7b42b7
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 7f01323e-6539-443b-bfff-7694d1ac8475
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders-329b0801-900b-42db-b17e-d0d159ec6674 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\M1097481\Downloads\Sample - Superstore csv.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

